/**
 * seed-prod.ts — Seed de producción para CEFIDE.
 *
 * Idempotente: usa upsert/createMany skipDuplicates. Seguro de correr
 * múltiples veces en un mismo base de datos.
 *
 * Qué seed:
 *   - ConfigSistema con valores reales
 *   - Actividades reales del gimnasio
 *   - Profesor Juan Pérez (data real del dump)
 *   - Todos los alumnos reales importados (≈300)
 *   - Inscripciones de alumnos (estado inicial: sin clases asignadas,
 *     el admin las configura vía el panel tras el deploy)
 *
 * Qué NO seed:
 *   - Usuario ADMIN: lo crea AdminSeedService en cada boot via ADMIN_EMAIL/ADMIN_PASSWORD
 *   - Passwords de profesores: requieren definición explícita antes del deploy
 *   - Ingresos/Pagos históricos: restaurar desde dump si se necesitan
 *
 * Uso:
 *   pnpm --filter backend exec ts-node --project tsconfig.json -e "
 *     require('ts-node/register'); require('./prisma/seed-prod.ts');
 *   "
 *   — o configurar en package.json: "prisma": { "seed": "ts-node prisma/seed-prod.ts" }
 */

import { PrismaClient, Frecuencia, Rol } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Actividades reales de CEFIDE (del dump 20260728, excluye registros dev)
// ---------------------------------------------------------------------------
const ACTIVIDADES = [
  'AERO',
  'APARATOS',
  'GIMNASIO',
  'ESCALADA',
  'General',
  'CROSS TRAINING',
  'PILATES',
];

// ---------------------------------------------------------------------------
// Alumnos reales (importados del CSV original, dump 20260728)
// Excluye los 4 registros de dev: 40111222, 40333444, 40555666, 40777888
// ---------------------------------------------------------------------------
const ALUMNOS: { dni: string; nombre: string; apellido: string; activo: boolean }[] = [
  { dni: '28673492', nombre: 'Gabriela', apellido: 'Carignani', activo: true },
  { dni: '24007106', nombre: 'Natalia', apellido: 'De Felipe', activo: true },
  { dni: '13587859', nombre: 'Mirta', apellido: 'Defelippo', activo: true },
  { dni: '12193116', nombre: 'Clide', apellido: 'Roche', activo: true },
  { dni: '27739759', nombre: 'Marina', apellido: 'Zampedri', activo: true },
  { dni: '20642611', nombre: 'Tomas', apellido: 'Dunda', activo: true },
  { dni: '4687397', nombre: 'Hector', apellido: 'Hernandez', activo: true },
  { dni: '4850902', nombre: 'Juan Carlos', apellido: 'Maggi', activo: true },
  { dni: '17007684', nombre: 'Maria Dolores', apellido: 'Diaz', activo: true },
  { dni: '18116358', nombre: 'Marcos', apellido: 'Merlino', activo: true },
  { dni: '16695237', nombre: 'Gladys', apellido: 'Torrens', activo: true },
  { dni: '13100218', nombre: 'Roberto', apellido: 'Luciano', activo: true },
  { dni: '23476206', nombre: 'Michel', apellido: 'Linlaud', activo: true },
  { dni: '25715489', nombre: 'Maria Sol', apellido: 'Agusti', activo: true },
  { dni: '16109869', nombre: 'Manuel', apellido: 'Baka', activo: true },
  { dni: '16049587', nombre: 'Ruben', apellido: 'Sironi', activo: true },
  { dni: '25715008', nombre: 'Mara', apellido: 'Raffaele', activo: true },
  { dni: '31994804', nombre: 'Mariano', apellido: 'Ines', activo: true },
  { dni: '22435011', nombre: 'Estela', apellido: 'Carballo', activo: true },
  { dni: '15565055', nombre: 'Diego', apellido: 'Galante', activo: true },
  { dni: '22435534', nombre: 'Alejandra', apellido: 'Radwansky', activo: true },
  { dni: '27415512', nombre: 'Ivan', apellido: 'Stoppani', activo: true },
  { dni: '16538170', nombre: 'Marisa', apellido: 'Jeich', activo: true },
  { dni: '30026069', nombre: 'M.de Los Angele', apellido: 'Armellini', activo: true },
  { dni: '26761442', nombre: 'M. Evangelina(a2)', apellido: 'Chungo', activo: true },
  { dni: '14115222', nombre: 'Jose Osmar', apellido: 'Scaglia', activo: true },
  { dni: '33427154', nombre: 'Nicolas', apellido: 'Rodriguez', activo: true },
  { dni: '16595379', nombre: 'Laura Ana', apellido: 'Leguizamon', activo: true },
  { dni: '27816988', nombre: 'Maria Florencia', apellido: 'Acosta', activo: true },
  { dni: '24062892', nombre: 'Sebastian(a', apellido: 'Lascialandare', activo: true },
  { dni: '34109309', nombre: 'Maria', apellido: 'Defelippo', activo: true },
  { dni: '17139394', nombre: 'Ariel', apellido: 'Villalba', activo: true },
  { dni: '20017795', nombre: 'Claudio', apellido: 'Ouakim', activo: true },
  { dni: '12028620', nombre: 'Susana', apellido: 'Piuma', activo: true },
  { dni: '36604064', nombre: 'Bruno', apellido: 'Contartese', activo: true },
  { dni: '13100307', nombre: 'Daniel', apellido: 'Negro', activo: true },
  { dni: '5608252', nombre: 'Eva', apellido: 'Fajoli', activo: true },
  { dni: '14320913', nombre: 'Jose Maria', apellido: 'Quintana', activo: true },
  { dni: '4541467', nombre: 'Marta', apellido: 'Fajoli', activo: true },
  { dni: '22435939', nombre: 'Paula A2', apellido: 'Suarez', activo: true },
  { dni: '93154297', nombre: 'Lucia', apellido: 'Tattangelo', activo: true },
  { dni: '17399706', nombre: 'Tomas', apellido: 'Pellilli', activo: true },
  { dni: '15410560', nombre: 'Juan Carlos', apellido: 'Inda', activo: true },
  { dni: '4542124', nombre: 'Ester', apellido: 'Caturla', activo: true },
  { dni: '36003215', nombre: 'Manuel', apellido: 'Torres', activo: true },
  { dni: '21890733', nombre: 'Claudia', apellido: 'Herrera', activo: true },
  { dni: '11547872', nombre: 'Eliana', apellido: 'Pauluzzi', activo: true },
  { dni: '8356457', nombre: 'Alfredo Arman', apellido: 'Sciaini', activo: true },
  { dni: '18478010', nombre: 'Dante', apellido: 'Faucetta', activo: true },
  { dni: '29771309', nombre: 'Martin Fern', apellido: 'Gozdiewski', activo: true },
  { dni: '12188949', nombre: 'Zulema', apellido: 'Gorosito', activo: true },
  { dni: '31609735', nombre: 'Maria Gimena', apellido: 'Vazquez', activo: true },
  { dni: '28673938', nombre: 'Ileana', apellido: 'Zandalazini', activo: true },
  { dni: '23262662', nombre: 'Carlos Horacio', apellido: 'Delgado', activo: true },
  { dni: '7692684', nombre: 'Hugo', apellido: 'Catalin', activo: true },
  { dni: '34109494', nombre: 'Gabriela', apellido: 'Gamerro', activo: true },
  { dni: '6141505', nombre: 'Oscar', apellido: 'Vercelli', activo: true },
  { dni: '31152815', nombre: 'Francisco(h)', apellido: 'Robles', activo: true },
  { dni: '36261560', nombre: 'Guillermo', apellido: 'Ariaca', activo: true },
  { dni: '16843768', nombre: 'Raul Marcelo', apellido: 'Lopez', activo: true },
  { dni: '33369661', nombre: 'Agustin', apellido: 'Isoardi', activo: true },
  { dni: '21890493', nombre: 'Clarisa/aero', apellido: 'Marcatelli', activo: true },
  { dni: '28276463', nombre: 'Ivan', apellido: 'Zuelgaray', activo: true },
  { dni: '4187543', nombre: 'Irma', apellido: 'Foresto', activo: true },
  { dni: '27816995', nombre: 'Leandro', apellido: 'Toledo', activo: true },
  { dni: '18116525', nombre: 'Pablo', apellido: 'Bonelli', activo: true },
  { dni: '17007704', nombre: 'German', apellido: 'Cabrera', activo: true },
  { dni: '16049614', nombre: 'Marta', apellido: 'Vigo', activo: true },
  { dni: '31042722', nombre: 'Juan Pablo', apellido: 'Penini', activo: true },
  { dni: '6207755', nombre: 'Ana Maria', apellido: 'Landeuix', activo: true },
  { dni: '28502208', nombre: 'Julian', apellido: 'Bande', activo: true },
  { dni: '4667978', nombre: 'Alberto', apellido: 'Plattoni', activo: true },
  { dni: '27560918', nombre: 'Gaston', apellido: 'Marcone', activo: true },
  { dni: '26512835', nombre: 'Magali', apellido: 'Tupone', activo: true },
  { dni: '4542331', nombre: 'Ma.del Carmen', apellido: 'Bossi', activo: true },
  { dni: '12028642', nombre: 'Monica', apellido: 'Coolican', activo: true },
  { dni: '24505742', nombre: 'Mauro', apellido: 'Lagostena', activo: true },
  { dni: '8427624', nombre: 'Rene', apellido: 'Hegouaburu', activo: true },
  { dni: '11817218', nombre: 'Monica', apellido: 'Lacentra', activo: true },
  { dni: '18116311', nombre: 'Fernando Javier', apellido: 'Lima', activo: true },
  { dni: '17603892', nombre: 'German', apellido: 'Poato', activo: true },
  { dni: '17399981', nombre: 'Miguel/escalada', apellido: 'Vanni', activo: true },
  { dni: '3994963', nombre: 'Marta', apellido: 'Dvorak', activo: true },
  { dni: '10713322', nombre: 'Monica/aero', apellido: 'Santilli', activo: true },
  { dni: '22753781', nombre: 'Ma. Jose', apellido: 'Cortagerena', activo: true },
  { dni: '13037243', nombre: 'Ana Maria', apellido: 'Martinez', activo: true },
  { dni: '5983594', nombre: 'Antonio Jose', apellido: 'Figueroa', activo: true },
  { dni: '34205532', nombre: 'Gabriel', apellido: 'Tomassini', activo: true },
  { dni: '28394956', nombre: 'Lucas', apellido: 'Gallardo', activo: true },
  { dni: '4258059', nombre: 'Beatriz', apellido: 'Benedicto', activo: true },
  { dni: '18361685', nombre: 'Edgardo', apellido: 'Gramet', activo: true },
  { dni: '10371358', nombre: 'Adrian Alberto', apellido: 'Peri', activo: true },
  { dni: '22435265', nombre: 'Andrea', apellido: 'Superti', activo: true },
  { dni: '28770935', nombre: 'Federico/profe', apellido: 'Tiseira', activo: true },
  { dni: '21525307', nombre: 'Pablo', apellido: 'Tambutto', activo: true },
  { dni: '20459971', nombre: 'Liliana', apellido: 'Troffe', activo: true },
  { dni: '28276855', nombre: 'M.candela', apellido: 'Ferrieri', activo: true },
  { dni: '28978403', nombre: 'Hernan', apellido: 'Martin', activo: true },
  { dni: '16093018', nombre: 'Ernesto', apellido: 'Albitre', activo: true },
  { dni: '16695038', nombre: 'Diego', apellido: 'Distilio', activo: true },
  { dni: '17891612', nombre: 'Gabriel', apellido: 'Marin', activo: true },
  { dni: '21825602', nombre: 'Mariela', apellido: 'Rolon', activo: true },
  { dni: '20017534', nombre: 'Roberto', apellido: 'Chervo', activo: true },
  { dni: '23262849', nombre: 'Gabriela(a2)', apellido: 'Ansaloni', activo: true },
  { dni: '29772094', nombre: 'Marianela', apellido: 'Caffiero', activo: true },
  { dni: '24007450', nombre: 'Maria Lorena', apellido: 'Chiochi', activo: true },
  { dni: '26761245', nombre: 'Mariano', apellido: 'Bilos', activo: true },
  { dni: '31152785', nombre: 'Ma.lujan(aero)', apellido: 'Nazziconi', activo: true },
  { dni: '17242241', nombre: 'Patricia', apellido: 'Demartini', activo: true },
  { dni: '25492909', nombre: 'Alfredo', apellido: 'Perazo', activo: true },
  { dni: '8278252', nombre: 'Hilario', apellido: 'Brandolisio', activo: true },
  { dni: '21022327', nombre: 'Ma.marcela', apellido: 'Herrera', activo: true },
  { dni: '20017820', nombre: 'Guillermo', apellido: 'Di Giacinti', activo: true },
  { dni: '22435086', nombre: 'Eduardo', apellido: 'De Felipe', activo: true },
  { dni: '30557336', nombre: 'Matias/cross', apellido: 'Sturiale', activo: true },
  { dni: '16208453', nombre: 'Ricardo', apellido: 'Berreta', activo: true },
  { dni: '28058492', nombre: 'Leonardo', apellido: 'Bluhn', activo: true },
  { dni: '22955764', nombre: 'Cecilia/aero', apellido: 'Scolara', activo: true },
  { dni: '13587066', nombre: 'Anibal', apellido: 'Soria', activo: true },
  { dni: '10231115', nombre: 'Alfredo', apellido: 'Anduaga', activo: true },
  { dni: '26512316', nombre: 'Gustavo', apellido: 'Wiengreen', activo: true },
  { dni: '30026376', nombre: 'Esteban', apellido: 'Boric', activo: true },
  { dni: '20459477', nombre: 'Ma.de Los Angeles', apellido: 'Troffe', activo: true },
  { dni: '20642287', nombre: 'Alejandra', apellido: 'Diamante', activo: true },
  { dni: '24505224', nombre: 'Fernando', apellido: 'Iriart', activo: true },
  { dni: '27742550', nombre: 'Viña Adrian', apellido: 'Fernandez', activo: true },
  { dni: '17539034', nombre: 'Luis', apellido: 'Bandera', activo: true },
  { dni: '22954157', nombre: 'Julian', apellido: 'Mutti', activo: true },
  { dni: '46000519', nombre: 'Juan', apellido: 'Ondarchu', activo: true },
  { dni: '11547917', nombre: 'Rogelio', apellido: 'Ortega', activo: true },
  { dni: '21416412', nombre: 'Ramiro', apellido: 'Primucci', activo: true },
  { dni: '24210861', nombre: 'Soledad', apellido: 'Guido', activo: true },
  { dni: '16193828', nombre: 'Rosalia', apellido: 'Venzi', activo: true },
  { dni: '13587127', nombre: 'Ruben', apellido: 'Cauhape', activo: true },
  { dni: '14545344', nombre: 'Mimi', apellido: 'Perez', activo: true },
  { dni: '17539085', nombre: 'Patricia', apellido: 'Luquez', activo: true },
  { dni: '17891589', nombre: 'Laura Carmen', apellido: 'Aroza', activo: true },
  { dni: '24210355', nombre: 'Carolina', apellido: 'Rossi', activo: true },
  { dni: '21525839', nombre: 'Claudia', apellido: 'Sbaffo', activo: true },
  { dni: '22954310', nombre: 'Cabe Evangelina', apellido: 'Mac', activo: true },
  { dni: '18742364', nombre: 'Yaquelin', apellido: 'Marengo', activo: true },
  { dni: '4688767', nombre: 'Luis', apellido: 'Re', activo: true },
  { dni: '18424678', nombre: 'Claudia A2', apellido: 'Alvarez', activo: true },
  { dni: '23105735', nombre: 'Victor', apellido: 'Martinez', activo: true },
  { dni: '29559244', nombre: 'Natalia', apellido: 'Tormo', activo: true },
  { dni: '6306460', nombre: 'Jorge Antonio', apellido: 'Luraschi', activo: true },
  { dni: '11678050', nombre: 'Isidro', apellido: 'Bravo', activo: true },
  { dni: '12519844', nombre: 'Marcela', apellido: 'Diaz', activo: true },
  { dni: '28450342', nombre: 'Aldo', apellido: 'Barraza', activo: true },
  { dni: '26126253', nombre: 'Maria Eugenia', apellido: 'Abud', activo: true },
  { dni: '20425772', nombre: 'Hernan', apellido: 'Calvo', activo: true },
  { dni: '29559130', nombre: 'Juan Pablo', apellido: 'Cesari', activo: true },
  { dni: '31587512', nombre: 'Carla', apellido: 'Lanchiotti', activo: true },
  { dni: '18425377', nombre: 'Silvana', apellido: 'Fonseca', activo: true },
  { dni: '13587200', nombre: 'Jorge Omar', apellido: 'Funes', activo: true },
  { dni: '6135157', nombre: 'De G Margarita', apellido: 'Aleman', activo: true },
  { dni: '27560683', nombre: 'Eduardo', apellido: 'Gutierrez', activo: true },
  { dni: '18336271', nombre: 'Sandra Laura', apellido: 'Zarate', activo: true },
  { dni: '17733345', nombre: 'Daniel', apellido: 'Luchelli', activo: true },
  { dni: '26800491', nombre: 'Ma. Guadalupe', apellido: 'Lopez', activo: true },
  { dni: '20459570', nombre: 'Nancy', apellido: 'Lopez', activo: true },
  { dni: '27560726', nombre: 'Federico', apellido: 'Marano', activo: true },
  { dni: '21006120', nombre: 'Claudio', apellido: 'Mina', activo: true },
  { dni: '17733202', nombre: 'Sergio', apellido: 'Pellegrini', activo: true },
  { dni: '5470050', nombre: 'Alicia', apellido: 'Perez', activo: true },
  { dni: '26125885', nombre: 'Gabriel', apellido: 'Tronchoni', activo: true },
  { dni: '11547963', nombre: 'Patricia/secre', apellido: 'Zarate', activo: true },
  { dni: '17241908', nombre: 'Javier', apellido: 'Rovai', activo: true },
  { dni: '21525405', nombre: 'Javier', apellido: 'Cairo', activo: true },
  { dni: '23262774', nombre: 'Diego', apellido: 'Correa', activo: true },
  { dni: '4690907', nombre: 'Carlos Albert', apellido: 'Cortagerena', activo: true },
  { dni: '17733296', nombre: 'Gabriel', apellido: 'Colagiovanni', activo: true },
  { dni: '16226999', nombre: 'Adriana/aero', apellido: 'Visciarelli', activo: true },
  { dni: '5466545', nombre: 'Lucia', apellido: 'Braida', activo: true },
  { dni: '27817350', nombre: 'Daniela', apellido: 'Filippini', activo: true },
  { dni: '25492436', nombre: 'Juan Cruz', apellido: 'Alimena', activo: true },
  { dni: '4694973', nombre: 'Martin', apellido: 'Caisson', activo: true },
  { dni: '26761777', nombre: 'Mariano', apellido: 'Mosca', activo: true },
  { dni: '24007889', nombre: 'Maria Soledad', apellido: 'Beban', activo: true },
  { dni: '22928489', nombre: 'Pablo Fernando', apellido: 'Miraglia', activo: true },
  { dni: '22435412', nombre: 'Laura/aero', apellido: 'Tizzano', activo: true },
  { dni: '18368897', nombre: 'Ma.de Los A', apellido: 'Ragolia', activo: true },
  { dni: '30688724', nombre: 'Federico', apellido: 'Casella', activo: true },
  { dni: '33499540', nombre: 'Ximena/aero', apellido: 'Noguera', activo: true },
  { dni: '4680112', nombre: 'Roberto', apellido: 'Bocanera', activo: true },
  { dni: '23476381', nombre: 'Ma.laura/profe', apellido: 'Bruschi', activo: true },
  { dni: '22079465', nombre: 'Jorgelina', apellido: 'Rossi', activo: true },
  { dni: '26512153', nombre: 'Marcos', apellido: 'Chamorro', activo: true },
  { dni: '30613318', nombre: 'Carlos', apellido: 'Medina', activo: true },
  { dni: '35114564', nombre: 'Emanuel', apellido: 'Cariaga', activo: true },
  { dni: '31363673', nombre: 'Sebastian', apellido: 'Escudero', activo: true },
  { dni: '31604577', nombre: 'Matias', apellido: 'Ruggeri', activo: true },
  { dni: '26681780', nombre: 'Lisandro', apellido: 'Suarez', activo: true },
  { dni: '22545163', nombre: 'Norma', apellido: 'Solterman', activo: true },
  { dni: '12519533', nombre: 'Jose', apellido: 'Aroza', activo: true },
  { dni: '25925066', nombre: 'Gaston', apellido: 'Petri', activo: true },
  { dni: '24268735', nombre: 'Mariana', apellido: 'Morandini', activo: true },
  { dni: '12460632', nombre: 'Luis', apellido: 'Visciarelli', activo: true },
  { dni: '6479740', nombre: 'Miguela', apellido: 'Staffora', activo: true },
  { dni: '14094775', nombre: 'Delia', apellido: 'Franco', activo: true },
  { dni: '30572469', nombre: 'Gaston', apellido: 'Luciano', activo: true },
  { dni: '38587134', nombre: 'Sonia Ines', apellido: 'Poggio', activo: true },
  { dni: '34300200', nombre: 'Pamela', apellido: 'Vergara', activo: true },
  { dni: '26472834', nombre: 'Juan Cruz', apellido: 'Correnti', activo: true },
  { dni: '34752526', nombre: 'Annabella(a2)', apellido: 'Ragolia', activo: true },
  { dni: '31718388', nombre: 'Federico', apellido: 'Galimberti', activo: true },
  { dni: '32594834', nombre: 'Nicolas', apellido: 'Alderete', activo: true },
  { dni: '15516040', nombre: 'Matias', apellido: 'Garavano', activo: true },
  { dni: '31909152', nombre: 'Melina', apellido: 'Ferraro', activo: true },
  { dni: '17452492', nombre: 'Cecilia/secre', apellido: 'Rebori', activo: true },
  { dni: '22592225', nombre: 'Ma. Veronica(a2)', apellido: 'Charre', activo: true },
  { dni: '11547750', nombre: 'Patricia', apellido: 'Catania', activo: true },
  { dni: '30572255', nombre: 'Maria Lujan', apellido: 'Almada', activo: true },
  { dni: '26125910', nombre: 'Maria Sol(a2)', apellido: 'Ocanto', activo: true },
  { dni: '24832273', nombre: 'Martin', apellido: 'Petinari', activo: true },
  { dni: '18578187', nombre: 'Jose', apellido: 'Linardos', activo: true },
  { dni: '18336291', nombre: 'Silvia', apellido: 'Del Fedele', activo: true },
  { dni: '17139500', nombre: 'Francisco', apellido: 'Yunis', activo: true },
  { dni: '24007794', nombre: 'Ivan', apellido: 'Chaparro', activo: true },
  { dni: '23262147', nombre: 'Virginia', apellido: 'Bautista', activo: true },
  { dni: '33123385', nombre: 'Jonatan', apellido: 'Villalva', activo: true },
  { dni: '36053835', nombre: 'Walter', apellido: 'Fregoso', activo: true },
  { dni: '8103293', nombre: 'German', apellido: 'Gerez', activo: true },
  { dni: '16595185', nombre: 'Patricia', apellido: 'Affonso', activo: true },
  { dni: '32279207', nombre: 'Agustin', apellido: 'Zanini', activo: true },
  { dni: '12112616', nombre: 'Clay Eduardo', apellido: 'Mac', activo: true },
  { dni: '26429840', nombre: 'Carolina/aero', apellido: 'Alva', activo: true },
  { dni: '25715843', nombre: 'Gustavo/cross T', apellido: 'Lescano', activo: true },
  { dni: '20116050', nombre: 'Luis Alberto', apellido: 'Arias', activo: true },
  { dni: '28276569', nombre: 'Juan Martin', apellido: 'Sanchez', activo: true },
  { dni: '36572234', nombre: 'Jazmin', apellido: 'Zanini', activo: true },
  { dni: '26388980', nombre: 'Silvio', apellido: 'Longinotti', activo: true },
  { dni: '33852169', nombre: 'Sebastian', apellido: 'Cappa', activo: true },
  { dni: '18411317', nombre: 'Adriana(a2)', apellido: 'Ajler', activo: true },
  { dni: '17308265', nombre: 'Cristina', apellido: 'Solis', activo: true },
  { dni: '10933599', nombre: 'Ramon', apellido: 'Gorosito', activo: true },
  { dni: '10371500', nombre: 'Abel', apellido: 'Tessi', activo: true },
  { dni: '10413322', nombre: 'Monica', apellido: 'Santilli', activo: true },
  { dni: '35070254', nombre: 'Aldana', apellido: 'Aguirre', activo: true },
  { dni: '29771255', nombre: 'Claudio', apellido: 'Di Rico', activo: true },
  { dni: '31257641', nombre: 'Juliana', apellido: 'Oggero', activo: true },
  { dni: '21434427', nombre: 'Liliana', apellido: 'Lalli', activo: true },
  { dni: '33427043', nombre: 'Horacio', apellido: 'Ballatore', activo: true },
  { dni: '38849961', nombre: 'Araceli/aero', apellido: 'Urrustoy', activo: true },
  { dni: '5947863', nombre: 'Yolanda', apellido: 'Nass', activo: true },
  { dni: '22021157', nombre: 'Silvia', apellido: 'Arce', activo: true },
  { dni: '27121086', nombre: 'Maria Eugenia', apellido: 'Piva', activo: true },
  { dni: '30457152', nombre: 'Javier', apellido: 'Perassi', activo: true },
  { dni: '34452320', nombre: 'Nicolas', apellido: 'Costa', activo: true },
  { dni: '12029064', nombre: 'Jose', apellido: 'Rubies', activo: true },
  { dni: '18116365', nombre: 'Marcela', apellido: 'Alvarez', activo: true },
  { dni: '26126931', nombre: 'Dario', apellido: 'De Giacomo', activo: true },
  { dni: '38848828', nombre: 'Matias', apellido: 'Turchi', activo: true },
  { dni: '14898247', nombre: 'Jose Luis', apellido: 'Zanini', activo: true },
  { dni: '30683752', nombre: 'Pamela', apellido: 'Ghelfi', activo: true },
  { dni: '12519592', nombre: 'Francisco', apellido: 'Monllor', activo: true },
  { dni: '26512253', nombre: 'Maria Gracia', apellido: 'Galvan', activo: true },
  { dni: '3999940', nombre: 'Nilda', apellido: 'Gamarra', activo: true },
  { dni: '28450400', nombre: 'Pablo', apellido: 'Ortiz', activo: true },
  { dni: '31609729', nombre: 'Pablo', apellido: 'Mohlinger', activo: true },
  { dni: '7890574', nombre: 'Miguel', apellido: 'Marano', activo: true },
  { dni: '22954388', nombre: 'Adrian', apellido: 'Blassi', activo: true },
  { dni: '13587994', nombre: 'Daniel R', apellido: 'Rivarola', activo: true },
  { dni: '24210559', nombre: 'Martin', apellido: 'Simonatto', activo: true },
  { dni: '30683659', nombre: 'Juan Manuel', apellido: 'Lodolini', activo: true },
  { dni: '24714111', nombre: 'Liliana', apellido: 'Ojeda', activo: true },
  { dni: '40189524', nombre: 'Galo', apellido: 'Crigna', activo: true },
  { dni: '12822748', nombre: 'Enrique', apellido: 'Aguer', activo: true },
  { dni: '39920717', nombre: 'Maria Sol', apellido: 'Luchelli', activo: true },
  { dni: '4722713', nombre: 'Monica', apellido: 'Grunwaldt', activo: true },
  { dni: '24095171', nombre: 'Leandro', apellido: 'Herrero', activo: true },
  { dni: '35114903', nombre: 'Gaston', apellido: 'Cuadranti', activo: true },
  { dni: '11547551', nombre: 'Manuel', apellido: 'Guerra', activo: true },
  { dni: '38849560', nombre: 'Gaspar', apellido: 'Distilio', activo: true },
  { dni: '40492520', nombre: 'Genaro', apellido: 'Distilio', activo: true },
  { dni: '13882496', nombre: 'Haydee', apellido: 'Siles', activo: true },
  { dni: '13882612', nombre: 'Liliana', apellido: 'Onaindi', activo: true },
  { dni: '24210078', nombre: 'Buzzio Gonzalo', apellido: 'Gonzalez', activo: true },
  { dni: '32658162', nombre: 'Julia', apellido: 'Luciano', activo: true },
  { dni: '13587128', nombre: 'Noemi', apellido: 'Manavella', activo: true },
  { dni: '26938293', nombre: 'Maria Ines', apellido: 'Sisevich', activo: true },
  { dni: '10656154', nombre: 'Oscar', apellido: 'Simaro', activo: true },
  { dni: '10177175', nombre: 'Hugo', apellido: 'Ruybal', activo: true },
  { dni: '0809001', nombre: 'Sara', apellido: 'Parodi', activo: true },
  { dni: '34452392', nombre: 'Julieta', apellido: 'Zanini', activo: true },
  { dni: '4991807', nombre: 'Marta', apellido: 'Pelusa', activo: true },
  { dni: '32534187', nombre: 'Patricio', apellido: 'Blassi', activo: true },
  { dni: '25492905', nombre: 'Juan Pablo', apellido: 'Donatelli', activo: true },
  { dni: '4981294', nombre: 'Ma.rosa', apellido: 'Etchapresto', activo: true },
  { dni: '24714081', nombre: 'Luis', apellido: 'Ibañez', activo: true },
  { dni: '6644423', nombre: 'Juana', apellido: 'Camilion', activo: true },
  { dni: '34452378', nombre: 'Lucia', apellido: 'Dure', activo: true },
  { dni: '32443745', nombre: 'German', apellido: 'Koch', activo: true },
  { dni: '16843474', nombre: 'Amadeo/escalada', apellido: 'Molinaro', activo: true },
  { dni: '24714332', nombre: 'Rosana', apellido: 'Landoni', activo: true },
  { dni: '34738932', nombre: 'Luciano', apellido: 'Cuevas', activo: true },
  { dni: '24007964', nombre: 'Diego', apellido: 'Cabrera', activo: true },
  { dni: '15410942', nombre: 'Luis', apellido: 'Murado', activo: true },
  { dni: '27817045', nombre: 'Ansaloni Laura(a2)', apellido: 'Garcia', activo: true },
  { dni: '22899762', nombre: 'Renato', apellido: 'Bresciani', activo: true },
  { dni: '11678607', nombre: 'Silvia', apellido: 'Beltramo', activo: true },
  { dni: '4691575', nombre: 'Jose Alberto', apellido: 'Rodriguez', activo: true },
  { dni: '13334436', nombre: 'Jorge', apellido: 'Perez', activo: true },
  { dni: '18341309', nombre: 'Pablo', apellido: 'Ceraso', activo: true },
  { dni: '36003181', nombre: 'Yamil Rodrigo', apellido: 'Vivas', activo: true },
  { dni: '41489038', nombre: 'Victoria', apellido: 'Wuilloud', activo: true },
  { dni: '16594883', nombre: 'Dario', apellido: 'Beltran', activo: true },
  { dni: '23746191', nombre: 'Silvana', apellido: 'Crespo', activo: true },
  { dni: '38848800', nombre: 'Lucas', apellido: 'De Paoli', activo: true },
  { dni: '25492775', nombre: 'Carlos', apellido: 'Maldonado', activo: true },
  { dni: '12519160', nombre: 'Walter', apellido: 'Dotti', activo: true },
  { dni: '34141659', nombre: 'Magali/funcional', apellido: 'Marini', activo: true },
  { dni: '31756608', nombre: 'Gerardo', apellido: 'Voltattorni', activo: true },
  { dni: '35701533', nombre: 'Matias', apellido: 'Montesanto', activo: true },
  { dni: '44667350', nombre: 'Catalina', apellido: 'Contreras', activo: true },
  { dni: '16301775', nombre: 'Claudio', apellido: 'Rosales', activo: true },
  { dni: '32620490', nombre: 'Cristian', apellido: 'Waitzel', activo: true },
  { dni: '5414584', nombre: 'Noemi', apellido: 'Lerchundi', activo: true },
];

// ---------------------------------------------------------------------------
// Inscripciones del dump: (dniAlumno, nombreActividad, frecuencia)
// Estado inicial: clasesTotal=0, clasesUsadas=0, pagado=false
// El admin las configura vía el panel después del deploy.
// ---------------------------------------------------------------------------
const INSCRIPCIONES: { dniAlumno: string; actividad: string; frecuencia: Frecuencia }[] = [
  { dniAlumno: '28673492', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24007106', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13587859', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12193116', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27739759', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '20642611', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4687397', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4850902', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17007684', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18116358', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16695237', actividad: 'GIMNASIO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13100218', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '23476206', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '25715489', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16109869', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16049587', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '25715008', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31994804', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22435011', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '15565055', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22435534', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27415512', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16538170', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '30026069', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26761442', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '14115222', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '33427154', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16595379', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27816988', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24062892', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '34109309', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17139394', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '20017795', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12028620', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '36604064', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13100307', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '5608252', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '14320913', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4541467', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22435939', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '93154297', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17399706', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '15410560', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4542124', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '36003215', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '21890733', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '11547872', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '8356457', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18478010', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '29771309', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12188949', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31609735', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '28673938', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '23262662', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '7692684', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '34109494', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '6141505', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31152815', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '36261560', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16843768', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '33369661', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '21890493', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '28276463', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4187543', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27816995', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18116525', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17007704', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16049614', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31042722', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '6207755', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '28502208', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4667978', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27560918', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26512835', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4542331', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12028642', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24505742', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '8427624', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '11817218', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18116311', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17603892', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17399981', actividad: 'ESCALADA', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '3994963', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '10713322', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22753781', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13037243', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '5983594', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '34205532', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '28394956', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4258059', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18361685', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '10371358', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22435265', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '21525307', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '20459971', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '28276855', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '28978403', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16093018', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16695038', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17891612', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '21825602', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '20017534', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '23262849', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '29772094', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24007450', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26761245', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31152785', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17242241', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '25492909', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '8278252', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '21022327', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '20017820', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22435086', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '30557336', actividad: 'CROSS TRAINING', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16208453', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '28058492', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22955764', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13587066', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '10231115', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26512316', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '30026376', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '20459477', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '20642287', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24505224', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27742550', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17539034', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22954157', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '46000519', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '11547917', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '21416412', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24210861', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16193828', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13587127', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '14545344', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17539085', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17891589', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24210355', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '21525839', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22954310', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18742364', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4688767', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18424678', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '23105735', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '29559244', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '6306460', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '11678050', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12519844', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '28450342', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26126253', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '20425772', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '29559130', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31587512', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18425377', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13587200', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '6135157', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27560683', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18336271', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17733345', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26800491', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '20459570', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27560726', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '21006120', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17733202', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '5470050', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26125885', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17241908', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '21525405', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '23262774', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4690907', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17733296', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16226999', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '5466545', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27817350', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '25492436', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4694973', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26761777', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24007889', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22928489', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22435412', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18368897', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '30688724', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '33499540', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4680112', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22079465', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26512153', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '30613318', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '35114564', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31363673', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31604577', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26681780', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22545163', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12519533', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '25925066', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24268735', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12460632', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '6479740', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '14094775', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '30572469', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '38587134', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '34300200', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26472834', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '34752526', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31718388', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '32594834', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '15516040', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31909152', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22592225', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '11547750', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '30572255', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26125910', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24832273', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18578187', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18336291', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17139500', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24007794', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '23262147', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '33123385', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '36053835', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '8103293', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16595185', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '32279207', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12112616', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26429840', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '25715843', actividad: 'CROSS TRAINING', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '20116050', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '28276569', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '36572234', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26388980', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '33852169', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18411317', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '17308265', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '10933599', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '10371500', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '35070254', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '29771255', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31257641', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '21434427', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '33427043', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '38849961', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '5947863', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22021157', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27121086', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '30457152', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '34452320', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12029064', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18116365', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26126931', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '38848828', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '14898247', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '30683752', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12519592', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26512253', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '3999940', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '28450400', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31609729', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '7890574', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22954388', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13587994', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24210559', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '30683659', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24714111', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '40189524', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12822748', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '39920717', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4722713', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24095171', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '35114903', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '11547551', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '38849560', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '40492520', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13882496', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13882612', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24210078', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '32658162', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13587128', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '26938293', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '10656154', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '10177175', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '0809001', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '34452392', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4991807', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '32534187', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '25492905', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4981294', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24714081', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '6644423', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '34452378', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '32443745', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16843474', actividad: 'ESCALADA', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24714332', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '34738932', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '24007964', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '15410942', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '27817045', actividad: 'AERO', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '22899762', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '11678607', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '4691575', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '13334436', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '18341309', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '36003181', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '41489038', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16594883', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '23746191', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '38848800', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '25492775', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '12519160', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '34141659', actividad: 'General', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '31756608', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '35701533', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '44667350', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '16301775', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '32620490', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
  { dniAlumno: '5414584', actividad: 'APARATOS', frecuencia: Frecuencia.UNA_VEZ },
];

async function main() {
  console.log('=== SEED PRODUCCIÓN CEFIDE ===\n');

  // 1. Config
  await prisma.configSistema.upsert({
    where: { id: 'global' },
    update: {},
    create: {
      id: 'global',
      clasesGracia: 2,
      diaVencimiento: 5,
      clasesUnaVez: 5,
      clasesDosVeces: 9,
      clasesTresVeces: 13,
      clasesLibre: 30,
      tiempoVerde: 4,
      tiempoAmarillo: 5,
      tiempoRojo: 6,
      codigosComodin: '00000000,99999999',
    },
  });
  console.log('✓ ConfigSistema');

  // 2. Actividades
  for (const nombre of ACTIVIDADES) {
    await prisma.actividad.upsert({
      where: { nombre },
      update: {},
      create: { nombre },
    });
  }
  console.log(`✓ Actividades (${ACTIVIDADES.length}): ${ACTIVIDADES.join(', ')}`);

  // 3. Alumnos — createMany con skipDuplicates
  await prisma.alumno.createMany({
    data: ALUMNOS.map((a) => ({ ...a })),
    skipDuplicates: true,
  });
  console.log(`✓ Alumnos: ${ALUMNOS.length}`);

  // 4. Inscripciones — lookup por DNI y nombre de actividad
  const actividadMap = new Map(
    await prisma.actividad.findMany({ select: { id: true, nombre: true } }).then((a) =>
      a.map((x) => [x.nombre, x.id]),
    ),
  );
  const alumnoMap = new Map(
    await prisma.alumno.findMany({ select: { id: true, dni: true } }).then((a) =>
      a.map((x) => [x.dni, x.id]),
    ),
  );

  let inscCreadas = 0;
  let inscOmitidas = 0;
  for (const i of INSCRIPCIONES) {
    const alumnoId = alumnoMap.get(i.dniAlumno);
    const actividadId = actividadMap.get(i.actividad);
    if (!alumnoId || !actividadId) {
      console.warn(`  [SKIP] ${i.dniAlumno} → ${i.actividad} (no encontrado)`);
      inscOmitidas++;
      continue;
    }
    await prisma.inscripcionActividad.upsert({
      where: { alumnoId_actividadId: { alumnoId, actividadId } },
      update: {},
      create: {
        alumnoId,
        actividadId,
        frecuencia: i.frecuencia,
        clasesTotal: 0,
        clasesUsadas: 0,
        pagado: false,
      },
    });
    inscCreadas++;
  }
  console.log(`✓ Inscripciones: ${inscCreadas} creadas, ${inscOmitidas} omitidas`);

  // 5. Profesor de prueba (Juan Pérez del dump — puede eliminarse si no aplica a prod)
  const prof = await prisma.profesor.upsert({
    where: { dni: '12345678' },
    update: {},
    create: { dni: '12345678', nombre: 'Juan', apellido: 'Pérez' },
  });
  const profPassword = process.env.PROFE_PASSWORD;
  if (profPassword) {
    const hash = await bcrypt.hash(profPassword, 10);
    await prisma.usuario.upsert({
      where: { email: 'juan@cefide.com' },
      update: {},
      create: {
        email: 'juan@cefide.com',
        password: hash,
        rol: Rol.PROFESOR,
        profesorId: prof.id,
      },
    });
    console.log('✓ Profesor Juan Pérez (juan@cefide.com)');
  } else {
    console.log('⚠  Profesor Juan Pérez creado sin usuario (PROFE_PASSWORD no definido)');
  }

  console.log('\n=== Seed completado. Admin se crea en el boot via ADMIN_EMAIL/ADMIN_PASSWORD. ===');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
