ALTER TYPE "Frecuencia" ADD VALUE IF NOT EXISTS 'CLASE_SUELTA';
ALTER TYPE "Frecuencia" ADD VALUE IF NOT EXISTS 'CUATRO_VECES';
ALTER TYPE "Frecuencia" ADD VALUE IF NOT EXISTS 'CINCO_VECES';

ALTER TABLE "ConfigSistema"
ADD COLUMN "clasesSuelta" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "clasesCuatroVeces" INTEGER NOT NULL DEFAULT 17,
ADD COLUMN "clasesCincoVeces" INTEGER NOT NULL DEFAULT 21;
